FROM oven/bun AS base

FROM base AS prune
RUN bun add -g turbo
WORKDIR /app
COPY . .
RUN turbo prune @r8y/web --docker

FROM base AS install
WORKDIR /app
COPY --from=prune /app/out/json/ .
RUN bun install --frozen-lockfile

FROM base AS build
WORKDIR /app
COPY --from=install /app/node_modules ./node_modules
COPY --from=prune /app/out/full/ .
COPY tsconfig.base.json .
RUN bun run --filter @r8y/web build

FROM base AS runtime
WORKDIR /app
COPY --from=build /app/apps/web/build ./build
COPY --from=build /app/apps/web/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules
EXPOSE 8080
CMD ["bun", "run", "start"]
